### ISSUE TITLE
Installing issue (conflict dependency and mujoco-py problem)

### ISSUE THREAD

**Issue by duongnhatthang** [katerakelly/oyster#10]
I tried to install this project on my computer: Ubuntu 16.04, mujoco 150 + 131 installed (with key) correctly (used in other projects normally). I follow the instruction to install dependent packages via conda env create -f environment.yml. I met 2 issues:

1. jupyter-console==6.0.0 and ipython=6.5.0 have conflict requirements for prompt-toolkit==1.0.15 (so I commented out the jupyter-console requirement, which solved the problem).

2. I struggled a bit with mujoco (first-time) with the very brief instruction for mujoco part. After I installed mujoco 150 and mujoco-py 1.50.1.68 => python launch_experiment required mujoco 131. So I installed mujoco 131, which I met all sorts of errors that can only installed correctly with mujoco-py 0.5.7, but then, your code would run incorrectly with all sorts of new errors.
The solution is to install mujoco 150 normally and AFTER that, change MUJOCO_PY_MJPRO_PATH to the 131-directory.

Maybe you want to edit and include more instruction in the README for others.

**Comment by katerakelly** [comment]
Thank you for bringing this to my attention! 
I have updated the repo to fix these issues and have more instructions.
Let me know if you have further issues.
