### ISSUE TITLE
Half cheetah observations with self.get_body_com("torso").flat

### ISSUE THREAD

**Issue by IraKorshunova** [katerakelly/oyster#14]
Hello! I'm wondering if there are any good reasons for adding _self.get_body_com("torso").flat_ to the observations of half cheetah:
https://github.com/katerakelly/oyster/blob/master/rlkit/envs/half_cheetah.py#L9

It seems to me that it only complicates comparisons between methods which also use gym.
Thank you!

**Comment by katerakelly** [comment]
Nope, there is not a good reason for this! A little git archaeology shows that this difference goes back to differences between envs in rllab and gym. I'd expect the result to be the same, but I'm verifying this just to be sure.

**Comment by IraKorshunova** [comment]
thank you for the rllab reference! do you know the reason why they added it? I'm pretty sure that qpos without the x-coordinate and qvel is all you need.

**Comment by katerakelly** [comment]
I don't know why rllab chose to include it. It shouldn't matter for these experiments. Just to be sure, I just ran the cheetah-dir and cheetah-vel experiments without it and it achieves the same test returns as reported in the paper. I'll add a note in the code about this!
