### ISSUE TITLE
Issue with Reproducing Results

### ISSUE THREAD

**Issue by bernwang** [katerakelly/oyster#15]
Hello, great work on your paper! I am trying to reproduce the results but am having some issues for some environments, most notably for humanoid-dir and walker-rand-params. 

I'm running experiments on a machine with Ubuntu 18.04.4 LTS and TITAN RTX. I am trying to run on Ubuntu 16.04 (but not GPU) and am getting similar results. 

I have plots humanoid-dir and walker-rand-params. The blue curves are the results you uploaded to Dropbox; the orange is what I produced (I haven't ran them for that long but they look very different from what you had. I've tested from a clean clone of this repo  and am using the same configs. 

Do you have any idea why this is happening? Thanks in advance!

<img width="404" alt="Screen Shot 2020-05-13 at 12 49 25 PM" src="https://user-images.githubusercontent.com/13114311/81858258-4a81dd80-9518-11ea-881a-d238a9e62c7f.png">

<img width="432" alt="Screen Shot 2020-05-13 at 1 03 36 PM" src="https://user-images.githubusercontent.com/13114311/81859544-3c34c100-951a-11ea-98f4-e3ba1ad8b5ca.png">

**Comment by katerakelly** [comment]
Thanks for bringing this issue to our attention! Please see the latest two commits which fix the problem. Let us know if you have any other problems with code.
