### ISSUE TITLE
mean_reg_loss, std_reg_loss and pre_activation_reg_loss in training

### ISSUE THREAD

**Issue by chungshan** [katerakelly/oyster#19]
Hi, I saw `mean_reg_loss`, `std_reg_loss` and `pre_activation_reg_loss` in training
https://github.com/katerakelly/oyster/blob/44e20fddf181d8ca3852bdf9b6927d6b8c6f48fc/rlkit/torch/sac/sac.py#L244
I didn't see them in paper. What are they for?

**Comment by katerakelly** [comment]
Hi, these are regularization losses from the Soft Actor-Critic (SAC) algorithm. We did not tune them and simply used the weights from the original SAC implementation. In fact, the `policy_pre_activation_weight=0` so that one is not used.
