### ISSUE TITLE
Is mujoco 1.3.1 really necessary?

### ISSUE THREAD

**Issue by pengzhenghao** [katerakelly/oyster#20]
Hi there, I am not sure whether the repo `rand_param_envs` explicitly change anything about gym or mujoco. Now I can run the code, by simply changing the script from:

`from rand_param_envs.gym import utils`

to 

`from gym import utils` (my gym is the latest one)

and so on, and the code is running smoothly.

So may I ask do you change anything about gym, mujoco_py, MujocoEnv from the original code? If not, then I think it's ok for me to use the official version of gym and mujoco (so that I don't need to install mujoco131..)

Thanks!

**Comment by katerakelly** [comment]
I believe that `rand_param_envs` relies on some aspect of MuJoCo 131 and earlier versions to properly implement the joint parameter randomization for the Walker and Hopper experiments. However, I don't know what exactly that aspect is.  At any rate, I haven't checked if the parameters actually change the way we would expect if using a later MuJoCo version, so it would be worth verifying that if you use a later version.
