### ISSUE TITLE
RL2 benchmark

### ISSUE THREAD

**Issue by janbolle** [katerakelly/oyster#23]
Dear @katerakelly and @azhou42,

Thank you for providing your code for your exciting paper!

You are stating:

> We ran our ProMP, MAML-TRPO, and RL2 baselines in the reference ProMP repo 

But I cannot find the RL2 baselines.
Can you please give me a hint where to look?

I really appreciate any help you can provide.

**Comment by janbolle** [comment]
or any RL2 implementation?

**Comment by katerakelly** [comment]
In the ProMP repository, switch to branch `full_code`, then see the `run_scripts` folder for the RL2 scripts.
