### ISSUE TITLE
Default Parameters Paper <-> Repository

### ISSUE THREAD

**Issue by 0pss** [katerakelly/oyster#24]
Hello, 
First, thank you for your research! I am currently trying (and struggling a little) to reproduce your results on the HalfCheetahVel environment. I noticed some differences between the algorithm in your paper (https://arxiv.org/pdf/1903.08254.pdf, page 5) and the default settings in this repository, i.e. 
 - the KL loss is scaled by .1 in the default settings
 - the next observation is not included in the sampled context by default, whereas in the paper I got the impression the next observation would always be included in the context.

I would highly appreciate if you can make some statement about the effect of those differences. Is my assumption correct, that your results were produced with the default parameters from the repo?

Thank you in advance!

**Comment by katerakelly** [comment]
Hello,

The results in the paper were produced with the default settings in this repository. If I remember correctly, the weight on the KL loss does make quite a difference, while adding the next observation in an environment where it's not needed (as in Cheetah-vel) doesn't make a difference - note that it **is** included in the Walker experiment in which the dynamics change across tasks.
