### ISSUE TITLE
About algorithm of PEARL

### ISSUE THREAD

**Issue by Zhikaiiii** [katerakelly/oyster#25]
Dear author, 
   In your paper you have mentioned that 'To achieve both meta-training efficiency and rapid adaptation, we propose an approach that integrates online inference of probabilistic context variables with existing off-policy RL algorithms'. So I wonder can I replace SAC with other algorithms such as DQN? If I can't , what is the reason. 
   Much thanks to you if you can reply my questions : )

**Comment by janbolle** [comment]
I am not an author, but maybe this helps.

The main idea here is to have a model (encoder) which gives us a latent representation of the underlying task. Using this latent representation we train an RL agent.
So I would say you can replace SAC, but if you change it to DQN you wouldn't be able to solve tasks with a continuous action space.
If you change it to PPO or any other on-policy algorithm you would trade the sample efficiency from SAC.

Hope this helps.

**Comment by Zhikaiiii** [comment]
> I am not an author, but maybe this helps.
> 
> The main idea here is to have a model (encoder) which gives us a latent representation of the underlying task. Using this latent representation we train an RL agent.
> So I would say you can replace SAC, but if you change it to DQN you wouldn't be able to solve tasks with a continuous action space.
> If you change it to PPO or any other on-policy algorithm you would trade the sample efficiency from SAC.
> 
> Hope this helps.

👍 much thanks to your advice : ) !

**Comment by hccz95** [comment]
> If you change it to PPO or any other on-policy algorithm you would trade the sample efficiency from SAC.

What if I change SAC to another off-policy actor-critic algorithm? Does the task inference still work?

**Comment by hccz95** [comment]
> I am not an author, but maybe this helps.
> 
> The main idea here is to have a model (encoder) which gives us a latent representation of the underlying task. Using this latent representation we train an RL agent. So I would say you can replace SAC, but if you change it to DQN you wouldn't be able to solve tasks with a continuous action space. If you change it to PPO or any other on-policy algorithm you would trade the sample efficiency from SAC.
> 
> Hope this helps.

hello, if I replace SAC by DQN in a discrete environment, does it work?
