### ISSUE TITLE
Questions about result figures

### ISSUE THREAD

**Issue by ligengen** [katerakelly/oyster#28]
Hi, I have a question of result figures in section 6 comparing six different benchmarks. The caption says that "Test-task performance vs. samples collected during meta-training". Is it **AverageReturn_all_test_tasks vs. Number of env steps total** in the progress.csv? I drew all of them but they can not always match. 

Also, how do you draw the figure with some light-colored shade? Does the shade mean the variance? If so, does it refer to the variance of 3 different random seeds' average return?

Also, I trained the ant-goal. The best return is -440, also have a big gap with your result (-200). But the rest of five is comparable. What it might be the reason?

Thank you in advance!

![Figure_2](https://user-images.githubusercontent.com/26115538/142615203-b81711a6-fc5a-4ff1-8005-1589eaa35f95.png)

<img width="994" alt="ori" src="https://user-images.githubusercontent.com/26115538/142615399-aa8112bb-7549-46b1-add3-82c7dfbe8424.png">

**Comment by XyDrKRulof** [comment]
The plots in the paper are a bit misleading. For the Ant-Goal-2D you have a total of ten milion steps, while for the other benchmarks you only have one milion steps. Your plot seems to be comparable to that of the paper if you take a look at the performance at around one milion steps
