### ISSUE TITLE
Computer got stuck when running 'humanoid-dir'

### ISSUE THREAD

**Issue by lujiayou123** [katerakelly/oyster#3]
When I ran the experiment'humanoid-dir', the computer got stuck in more than 200 iterations. This happened once before, I thought it was an accident , so I turned off the power  and rebooted forcibly. Then I found that the graphics driver was broken. So I reinstalled the graphics driver and tried again. Then the computer got stuck again.
 What may be the cause? 
My computer has 16GB memory, CPU 8700K, GPU 2080.

**Comment by katerakelly** [comment]
I haven't experienced a problem like this before. Have you run other MuJoCo environments? Have you run other codebases on the humanoid env?

**Comment by lujiayou123** [comment]
maybe 16GB memory is not enough

**Comment by katerakelly** [comment]
Closing as this seems like a more general issue than this codebase.
