### ISSUE TITLE
About the input of context encoder

### ISSUE THREAD

**Issue by zwfightzw** [katerakelly/oyster#4]
Pearl is an instructive paper.
However, in the comparison between the paper and the source code, I found one question, which is about the input of context encoder. In the paper, c={s, a, r, s'}, but in the source code, c={s, a, r}.
For such a design, how to analyze the impact of introducing s'?

**Comment by katerakelly** [comment]
Thank you for pointing this out. We have updated the code to include the option of including `s` in the context, which is necessary for task distributions in which the dynamics change across tasks (such as Walker and Hopper).
